trigger:
- main

pool:
  name: elad-pc

variables:
  - group: StorageSecrets
  - name: azureServiceConnection
    value: 'elad-service-connect'
  - name: resourceGroup
    value: 'elad-rg'
  - name: location
    value: 'eastus'
  - name: storageTemplate
    value: 'storage-template.json'
  - name: vmTemplate
    value: 'vm-template.json'
  - name: publicIpName
    value: 'elad-public-ip'
  - name: vmUser
    value: 'azureUser'
  - name: vmPublicIp
    value: '172.190.211.170'

stages:
- stage: Deploy_Resources
  displayName: Deploy Storage Accounts & VM
  jobs:
  - job: Deploy
    displayName: Deploy Storage and VM
    steps:
    
    - task: AzureCLI@2
      displayName: "Login to Azure"
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az account show  # Verify Azure authentication

    - task: AzureCLI@2
      displayName: "Deploy Storage Accounts"
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create --resource-group $(resourceGroup) `
          --template-file $(storageTemplate) `
          --parameters storageAccount1Name=eladstorageacct12345 storageAccount2Name=eladstorageacct67890 location=$(location)

    - task: AzureCLI@2
      displayName: "Deploy Virtual Machine"
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create --resource-group $(resourceGroup) `
          --template-file $(vmTemplate) `
          --parameters vmName=myVM adminUsername=$(vmUser) adminPassword='P@ssw0rd!' `
                       networkInterfaceName=myVMnic publicIpName=$(publicIpName) `
                       vnetName=elad-vnet subnetName=elad-subnet location=$(location)

- stage: Execute_Blob_Copy
  displayName: Execute Blob Copy Script on VM
  jobs:
  - job: RunBlobCopy
    displayName: Run Blob Copy Script on Azure VM
    steps:
    
    - task: SSH@0
      displayName: "Execute Blob Copy Script on VM"
      inputs:
        sshEndpoint: "sshvm"
        runOptions: "inline"
        inline: |
          echo "Executing blobs.py on the VM..."
          python3 /home/azureUser/scripts/blobs.py